// マスコットの名鑑。球団の顔として一体ずつガチャで迎える。特殊能力(ab)がシーズンに効く。
// 写真は tools/fetch_mascot.js が Wikimedia の自由ライセンスから拾い、mascot-photo.js に出典を残す。
const MASCOT_ABILITY = {
  cheer:  {name:"応援団長", icon:"📣", desc:"どんなに負けが込んでも士気が底を割らない(下限を保証)"},
  luck:   {name:"幸運",     icon:"🍀", desc:"開幕時に采配権が2回ぶん増える"},
  trick:  {name:"いたずら", icon:"😈", desc:"首位攻防戦や判定の場面で勝つと、相手の士気を7日間下げる"},
  crowd:  {name:"集客",     icon:"🎟", desc:"貯金が+5・+10・+15・+20に届くたびに+1点"},
  growth: {name:"育成",     icon:"🌱", desc:"若手や伏兵が覚醒しやすい"},
  guard:  {name:"守り神",   icon:"🛡", desc:"スキャンダルや珍事件の的になりにくい"},
  rally:  {name:"反撃",     icon:"🔥", desc:"4連敗以上のとき、打線の調子が上向く"},
  fortune:{name:"福の神",   icon:"🎁", desc:"野手ガチャでS以上を1枚保証(ガチャで球団を作るとき)"},
};
const MASCOTS = [
  // ---- 日本 ----
  {id:"tsubakuro", name:"つば九郎", team:"ヤクルト", fr:"ヤクルト", rank:"SS", ab:"trick", since:1994, desc:"畜生系マスコットの元祖。フリップ芸で球界を騒がせる燕。", ja:"つば九郎", en:"Tsubakuro", q:"Tsubakuro"},
  {id:"doala", name:"ドアラ", team:"中日", fr:"中日", rank:"SS", ab:"rally", since:1994, desc:"バク転の成否で球場の空気が変わる。中日の顔。", ja:"ドアラ", en:"Doala", q:"Doala"},
  {id:"torakky", name:"トラッキー", team:"阪神", fr:"阪神", rank:"S", ab:"cheer", since:1985, desc:"甲子園の熱狂を率いる虎。1985年の優勝とともに生まれた。", ja:"トラッキー", en:"To-Lucky", q:"To-Lucky Hanshin Tigers"},
  {id:"slyly", name:"スラィリー", team:"広島", fr:"広島", rank:"S", ab:"crowd", since:1995, desc:"赤い球場を沸かせる謎の生き物。フィリー・ファナティックの親戚。", ja:"スラィリー", en:"Slyly", q:"Slyly Hiroshima Carp"},
  {id:"starman", name:"DB.スターマン", team:"DeNA", fr:"DeNA", rank:"A", ab:"cheer", since:2012, desc:"ハマスタの星のマスコット。ゆるい動きで愛される。", ja:"DB.スターマン", q:"DB.Starman Yokohama"},
  {id:"giabbit", name:"ジャビット", team:"巨人", fr:"巨人", rank:"S", ab:"fortune", since:1992, desc:"巨人のうさぎ。背番号333。", ja:"ジャビット", en:"Giabbit", q:"Giabbit"},
  {id:"harryhawk", name:"ハリーホーク", team:"ソフトバンク", fr:"ソフトバンク", rank:"S", ab:"luck", since:1989, desc:"福岡の空を舞う鷹。ダイエー時代から球団を見守る。", ja:"ハリーホーク", en:"Harry Hawk", q:"Harry Hawk SoftBank Hawks"},
  {id:"leo", name:"レオ", team:"西武", fr:"西武", rank:"A", ab:"guard", since:1979, desc:"手塚治虫の「ジャングル大帝」から生まれたライオン。", ja:"レオ (西武ライオンズ)", q:"Leo Saitama Seibu Lions mascot"},
  {id:"markun", name:"マーくん", team:"ロッテ", fr:"ロッテ", rank:"A", ab:"cheer", since:1992, desc:"カモメのマスコット。幕張の海風に乗る。", ja:"マーくん", q:"Mar-kun Chiba Lotte Marines"},
  {id:"frep", name:"フレップ・ザ・フォックス", team:"日本ハム", fr:"日本ハム", rank:"A", ab:"growth", since:2016, desc:"北海道のキタキツネ。エスコンフィールドの新しい顔。", ja:"フレップ・ザ・フォックス", q:"Frep the Fox"},
  {id:"bull", name:"バファローブル", team:"オリックス", fr:"オリックス", rank:"A", ab:"rally", since:2011, desc:"オリックスの猛牛。大阪と神戸を駆け回る。", ja:"バファローブル", q:"Buffalo Bull Orix"},
  {id:"clutch", name:"クラッチ", team:"楽天", fr:"楽天", rank:"A", ab:"luck", since:2005, desc:"仙台の鷲。勝負強さの名を持つ。", ja:"クラッチ (マスコット)", q:"Clutch Rakuten Eagles mascot"},
  {id:"bb", name:"B・B", team:"日本ハム", fr:"日本ハム", rank:"B", ab:"crowd", since:2004, desc:"北海道移転後の初代マスコット。バク宙で沸かせた熊。", ja:"B・B (マスコット)", q:"B.B. Hokkaido Nippon-Ham Fighters mascot"},
  {id:"gyorotan", name:"ギョロタン", team:"日本ハム", fr:"日本ハム", rank:"C", ab:"trick", since:1981, desc:"東京時代のファイターズの怪獣。後楽園を歩いた。", ja:"ギョロタン"},
  {id:"buffilead", name:"バフィリード", team:"近鉄", fr:"近鉄", rank:"B", ab:"rally", since:1997, desc:"近鉄バファローズ最後のマスコット。", ja:"バフィリード"},
  {id:"bravy", name:"ブレービー", team:"阪急", fr:"オリックス", rank:"B", ab:"guard", since:1981, desc:"阪急ブレーブスの騎士。西宮球場の伝説。", ja:"ブレービー", q:"Bravy Hankyu Braves"},
  {id:"bell", name:"バファローベル", team:"オリックス", fr:"オリックス", rank:"B", ab:"cheer", since:2011, desc:"オリックスの牛の女の子。ブルの相棒。", ja:"バファローベル"},
  {id:"lucky", name:"ラッキー", team:"阪神", fr:"阪神", rank:"B", ab:"luck", since:1993, desc:"トラッキーの相方。虎の女の子。", ja:"ラッキー (阪神タイガース)", q:"Lucky Hanshin Tigers mascot"},
  {id:"hosshey", name:"ホッシー", team:"横浜", fr:"DeNA", rank:"B", ab:"fortune", since:1993, desc:"横浜ベイスターズ時代の星の妖精。", ja:"ホッシー (横浜ベイスターズ)", q:"Hosshey Yokohama BayStars"},
  {id:"carpboya", name:"カープ坊や", team:"広島", fr:"広島", rank:"A", ab:"cheer", since:1975, desc:"帽子とバットの少年。1975年初優勝の頃から球団の顔。", ja:"カープ坊や", q:"Carp Boya Hiroshima"},
  {id:"paolon", name:"パオロン", team:"中日", fr:"中日", rank:"C", ab:"guard", since:1997, desc:"ナゴヤドーム開場とともに登場した象。", ja:"パオロン"},
  // ---- MLB ----
  {id:"phanatic", name:"フィリー・ファナティック", team:"フィリーズ", fr:"MLB", rank:"SS", ab:"trick", since:1978, desc:"球界一のいたずら者。四輪バギーで球場を暴れ回る。", ja:"フィリー・ファナティック", en:"Phillie Phanatic", q:"Phillie Phanatic"},
  {id:"mrmet", name:"ミスター・メット", team:"メッツ", fr:"MLB", rank:"S", ab:"cheer", since:1964, desc:"野球ボールの頭を持つ紳士。1964年からの古株。", en:"Mr. Met", q:"Mr. Met"},
  {id:"moose", name:"マリナー・ムース", team:"マリナーズ", fr:"MLB", rank:"S", ab:"rally", since:1990, desc:"シアトルのヘラジカ。イチローと同じ外野を駆けた。", ja:"マリナー・ムース", en:"Mariner Moose", q:"Mariner Moose"},
  {id:"wally", name:"ウォーリー・ザ・グリーンモンスター", team:"レッドソックス", fr:"MLB", rank:"S", ab:"guard", since:1997, desc:"フェンウェイの緑の壁から生まれた。", en:"Wally the Green Monster", q:"Wally the Green Monster"},
  {id:"orbit", name:"オービット", team:"アストロズ", fr:"MLB", rank:"A", ab:"fortune", since:1990, desc:"宇宙から来た緑の生き物。ヒューストンの人気者。", en:"Orbit (mascot)", q:"Orbit Houston Astros mascot"},
  {id:"billy", name:"ビリー・ザ・マーリン", team:"マーリンズ", fr:"MLB", rank:"B", ab:"luck", since:1993, desc:"身長2.4メートルのカジキ。", en:"Billy the Marlin", q:"Billy the Marlin"},
  {id:"bernie", name:"バーニー・ブルワー", team:"ブルワーズ", fr:"MLB", rank:"A", ab:"crowd", since:1973, desc:"本塁打が出ると滑り台を滑り降りる。", en:"Bernie Brewer", q:"Bernie Brewer"},
  {id:"southpaw", name:"サウスポー", team:"ホワイトソックス", fr:"MLB", rank:"B", ab:"growth", since:2004, desc:"2005年世界一の年にデビューした緑の生き物。", en:"Southpaw (mascot)", q:"Southpaw White Sox mascot"},
  {id:"paws", name:"パウズ", team:"タイガース", fr:"MLB", rank:"B", ab:"guard", since:1995, desc:"デトロイトの虎。", en:"Paws (mascot)", q:"Paws Detroit Tigers mascot"},
  {id:"slider", name:"スライダー", team:"ガーディアンズ", fr:"MLB", rank:"B", ab:"trick", since:1990, desc:"クリーブランドの紫のふわふわ。", en:"Slider (mascot)", q:"Slider Cleveland mascot"},
  {id:"stomper", name:"ストンパー", team:"アスレチックス", fr:"MLB", rank:"B", ab:"rally", since:1997, desc:"アスレチックスの象。球団の古い象徴から。", en:"Stomper (mascot)", q:"Stomper Oakland Athletics"},
  {id:"raymond", name:"レイモンド", team:"レイズ", fr:"MLB", rank:"B", ab:"trick", since:1998, desc:"青い毛むくじゃらの「シードッグ」。", en:"Raymond (mascot)", q:"Raymond Tampa Bay Rays mascot"},
  {id:"screech", name:"スクリーチ", team:"ナショナルズ", fr:"MLB", rank:"C", ab:"cheer", since:2005, desc:"ワシントンの白頭鷲。", en:"Screech (mascot)", q:"Screech Washington Nationals"},
  {id:"dinger", name:"ディンガー", team:"ロッキーズ", fr:"MLB", rank:"B", ab:"fortune", since:1994, desc:"球場建設中に見つかった恐竜の卵から生まれた。", en:"Dinger (mascot)", q:"Dinger Colorado Rockies"},
  {id:"sluggerrr", name:"スラッガー", team:"ロイヤルズ", fr:"MLB", rank:"B", ab:"luck", since:1996, desc:"王冠をかぶったライオン。ホットドッグ砲で有名。", en:"Sluggerrr", q:"Sluggerrr Kansas City Royals"},
  {id:"captain", name:"キャプテン", team:"レンジャーズ", fr:"MLB", rank:"C", ab:"cheer", since:2002, desc:"テキサスの馬。", en:"Rangers Captain", q:"Rangers Captain mascot"},
  {id:"louseal", name:"ルー・シール", team:"ジャイアンツ", fr:"MLB", rank:"A", ab:"crowd", since:1996, desc:"サンフランシスコ湾のアシカ。", en:"Lou Seal", q:"Lou Seal"},
  {id:"friar", name:"スウィンギング・フライアー", team:"パドレス", fr:"MLB", rank:"B", ab:"growth", since:1958, desc:"バットを振る修道士。", en:"Swinging Friar", q:"Swinging Friar"},
  {id:"oriolebird", name:"オリオール・バード", team:"オリオールズ", fr:"MLB", rank:"B", ab:"luck", since:1979, desc:"ボルティモアのムクドリモドキ。", en:"The Oriole Bird", q:"Oriole Bird mascot"},
  {id:"tcbear", name:"TC・ベア", team:"ツインズ", fr:"MLB", rank:"C", ab:"guard", since:2000, desc:"ミネソタの熊。", en:"T.C. Bear", q:"T.C. Bear Twins"},
  {id:"ace", name:"エース", team:"ブルージェイズ", fr:"MLB", rank:"C", ab:"rally", since:2000, desc:"トロントの青いカケス。", en:"Ace (mascot)", q:"Ace Toronto Blue Jays mascot"},
  {id:"fredbird", name:"フレッドバード", team:"カージナルス", fr:"MLB", rank:"A", ab:"cheer", since:1979, desc:"セントルイスの赤い鳥。", en:"Fredbird", q:"Fredbird"},
  {id:"parrot", name:"パイレート・パロット", team:"パイレーツ", fr:"MLB", rank:"B", ab:"trick", since:1979, desc:"海賊のオウム。", en:"Pirate Parrot", q:"Pirate Parrot"},
  {id:"redlegs", name:"ミスター・レッドレッグス", team:"レッズ", fr:"MLB", rank:"B", ab:"fortune", since:2007, desc:"口ひげの野球ボール頭。1869年の最初のプロ球団にちなむ。", en:"Mr. Redlegs", q:"Mr. Redlegs"},
  {id:"clark", name:"クラーク", team:"カブス", fr:"MLB", rank:"B", ab:"growth", since:2014, desc:"リグレーの若い熊。", en:"Clark the Cub", q:"Clark the Cub"},
  {id:"blooper", name:"ブルーパー", team:"ブレーブス", fr:"MLB", rank:"C", ab:"trick", since:2018, desc:"アトランタのおどけ者。", en:"Blooper (mascot)", q:"Blooper Atlanta Braves mascot"},
  {id:"baxter", name:"D.バクスター", team:"ダイヤモンドバックス", fr:"MLB", rank:"C", ab:"luck", since:2000, desc:"砂漠のボブキャット。", en:"D. Baxter the Bobcat", q:"D. Baxter the Bobcat"},
  {id:"gapper", name:"ゲイパー", team:"レッズ", fr:"MLB", rank:"C", ab:"crowd", since:2002, desc:"シンシナティの赤い毛玉。", en:"Gapper", q:"Gapper Cincinnati Reds mascot"},
];
